title: Oluwatosin Oyekanmi
# logo: /assets/salamitosin.jpg
description: Dedicated professional with responsible data management, leadership and communication. Detail-oriented in problem solving and planning. Ready tomake an immediate contribution to your organization.
# show_downloads: true
theme: jekyll-theme-minimal
